[package]
name = "aoc"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "01"
path = "days/01.rs"

[[bin]]
name = "02"
path = "days/02.rs"

[[bin]]
name = "03"
path = "days/03.rs"

[dependencies]
regex="*"
