[package]
name = "aoc"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "01"
path = "days/01.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
